# Copyright(c) The Maintainers of Nanvix.
# Licensed under the MIT License.

[package]
name = "kernel"
version = "0.0.5"
license-file = "LICENSE.txt"
edition = "2021"
authors = ["The Maintainers of Nanvix"]
description = "Nanvix Kernel"
homepage = "https://github.com/nanvix"

[[bin]]
name = "kernel"
path = "src/kmain.rs"

[dependencies]
arch = { git = "https://github.com/nanvix/arch", version = "0.0.1" }
bitmap ={ git = "https://github.com/nanvix/bitmap" }
error = {git = "https://github.com/nanvix/error"}
raw-array = { git = "https://github.com/nanvix/raw-array" }
sys = { git = "https://github.com/nanvix/sys", tag = "v1.0.0"}

[features]
trace = []
