# Copyright(c) The Maintainers of Nanvix.
# Licensed under the MIT License.

[package]
name = "kernel"
version = "0.0.12"
license-file = "LICENSE.txt"
edition = "2021"
authors = ["The Maintainers of Nanvix"]
description = "Nanvix Kernel"
homepage = "https://github.com/nanvix"

[[bin]]
name = "kernel"
path = "src/kmain.rs"

[dependencies]
arch = { git = "https://github.com/nanvix/arch", branch = "releases/v1.0.0" }
bitmap = { git = "https://github.com/nanvix/bitmap", branch = "releases/v0.0.1" }
error = { git = "https://github.com/nanvix/error", branch = "releases/v0.0.1" }
raw-array = { git = "https://github.com/nanvix/raw-array", branch = "releases/v0.0.1" }
slab = { git = "https://github.com/nanvix/slab", branch = "releases/v0.0.1" }
sys = { git = "https://github.com/nanvix/sys", branch = "releases/v1.1.1" }

[features]
trace = []
